export async function getHistory() {
  return [
    {
      id: 0,
      authorName: "쓴 사람 이름입니다11",
      timeStamp: 18121312312,
      actionId: 0,
      todoTitle: "새로운 투두",
      todoSrc: null,
      todoDst: null,
    },
    {
      id: 1,
      authorName: "쓴 사람 이름입니다",
      timeStamp: 18121312312,
      actionId: 1,
      todoTitle: " 삭제한 투두",
      todoSrc: null,
      todoDst: null,
    },
    {
      id: 2,
      authorName: "쓴 사람 이름입니다",
      timeStamp: 18121312312,
      actionId: 3,
      todoTitle: "이동한 투두",
      todoSrc: "하고있는 일",
      todoDst: "해야하는 일",
    },
    {
      id: 2,
      authorName: "쓴 사람 이름입니다",
      timeStamp: 18121312312,
      actionId: 3,
      todoTitle: "이동한 투두",
      todoSrc: "하고있는 일",
      todoDst: "해야하는 일",
    },
    {
      id: 2,
      authorName: "쓴 사람 이름입니다",
      timeStamp: 18121312312,
      actionId: 3,
      todoTitle: "이동한 투두",
      todoSrc: "하고있는 일",
      todoDst: "해야하는 일",
    },
    {
      id: 2,
      authorName: "쓴 사람 이름입니다",
      timeStamp: 18121312312,
      actionId: 3,
      todoTitle: "이동한 투두",
      todoSrc: "하고있는 일",
      todoDst: "해야하는 일",
    },
  ];
}
